# Generated by Django 4.0.2 on 2022-02-13 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='value',
            field=models.CharField(max_length=100),
        ),
    ]
